"""empty message

Revision ID: 534bd5c26c87
Revises: 
Create Date: 2022-05-14 21:25:11.029294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "534bd5c26c87"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("persons")
    # ### end Alembic commands ###
